uploads = []
generated = []

[[outputs]]
id = "W8_1RRKmPddCLHlmf8pHg"
uri = "file://da-francesco-site.zip"
type = "unspecified"
title = "da-francesco-site.zip"

[[outputs]]
id = "na2i5YtpZLTb0b8NXv7X4"
uri = "file://workspace-full.tar.gz"
type = "unspecified"
title = "workspace-full.tar.gz — Workspace complet"

[[outputs]]
id = "SrwiY_2ffOtvtw_ejjrwm"
uri = "file://da-francesco-cod-sursa.zip"
type = "unspecified"
title = "da-francesco-cod-sursa.zip — Cod sursă complet (2.1 MB)"

[[outputs]]
id = "LblGjKjBjG5e9-p5TYedQ"
uri = "file://workspace-sursa.zip"
type = "unspecified"
title = "workspace-sursa.zip — Workspace complet (10.9 MB, 261 fișiere)"

[[outputs]]
id = "iAo2ZEx1vLp2G_vxLzRfz"
uri = "file://github-pages-dist.zip"
type = "unspecified"
title = "github-pages-dist.zip — Fișiere gata pentru GitHub Pages (2.1 MB)"
